services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/sunmh207/ai-codereview-gitlab:1.4.2
    ports:
      - "5001:5001"
      - "5002:5002"
    volumes:
      - /home/ai-codereview/data:/app/data
      - /home/ai-codereview/log:/app/log
      - ./conf/review_rule:/app/conf/review_rule
    env_file:
      - ./conf/.env
    restart: unless-stopped